FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
        cmake \
        ninja-build \
        git \
        ccache \
        g++ \
        gcc \
        autoconf \
        libtool
